#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config top_padding 30
bspc config bottom_padding 0
bspc config left_padding 2
bspc config right_padding 2
bspc config click_to_focus       	true
bspc config focus_follows_pointer	true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config border_radius 15


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#AutoStart
killall "nm-applet"  
picom &
nitrogen --restore &                         
~/.config/polybar/launch.sh &            
xinput set-prop 13 315 0.5 &       ##Touchpad speed
nm-applet &
